version: 6.0.{build}
branches:
  only:
  - master
image: Ubuntu1804
environment:
  DockerHubAccessToken:
    secure: VYKd4CaBJazTyU2VNPi0fAiKMtQcpOjwEMprUL7r6HJCeGL8ODKs+8zoo5PTIgOQ
build_script:
- sh: >-
    ./build-docker.sh ubuntu18.04 $APPVEYOR_BUILD_VERSION

    ./build-docker.sh ubuntu16.04 $APPVEYOR_BUILD_VERSION

    ./build-docker.sh centos7 $APPVEYOR_BUILD_VERSION

    ./build-docker.sh alpine3.8 $APPVEYOR_BUILD_VERSION

    ./build-docker.sh opensuse42.3 $APPVEYOR_BUILD_VERSION

    ./build-docker.sh fedora28 $APPVEYOR_BUILD_VERSION

test: off
deploy_script:
- sh: >-
    Prerelease=`pwsh -Command "([string]([bool](Import-PowerShellDataFile src/safeguard-ps.psd1).PrivateData.PSData.Prerelease)).ToLower()"`

    if $Prerelease; then

        echo "Not publishing docker images for pre-release"

    else

        docker login -u petrsnd -p $DockerHubAccessToken

        echo "TODO: docker publish"

        docker logout

    fi

notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: safeguard-ps build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
