version: 6.0.{build}
branches:
  only:
  - master
image: Ubuntu1804
build_script:
- sh: >-

    ./build-docker.sh ubuntu18.04 $env:APPVEYOR_BUILD_VERSION

    ./build-docker.sh ubuntu16.04 $env:APPVEYOR_BUILD_VERSION

    ./build-docker.sh centos7 $env:APPVEYOR_BUILD_VERSION

    ./build-docker.sh alpine3.8 $env:APPVEYOR_BUILD_VERSION

    ./build-docker.sh opensuse42.3 $env:APPVEYOR_BUILD_VERSION

    ./build-docker.sh fedora28 $env:APPVEYOR_BUILD_VERSION