version: 6.0.{build}
branches:
  only:
  - master
  - 6.0
image: Visual Studio 2019
environment:
  PsGalleryApiKey:
    secure: Zgbj3NNbLsk8NLMhVsztd6BUH80ZKq1eu/K43okCHzvahEW5tO5y6gInHp5UTBYm
  DockerHubAccessToken:
    secure: VYKd4CaBJazTyU2VNPi0fAiKMtQcpOjwEMprUL7r6HJCeGL8ODKs+8zoo5PTIgOQ
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    & .\install-appveyor.ps1

    Import-Module -Name safeguard-ps -Verbose

    if ([bool](Import-PowerShellDataFile (Join-Path (Get-Module safeguard-ps).ModuleBase safeguard-ps.psd1)).PrivateData.PSData.Prerelease) {

        Write-Host "Not building docker images for pre-release build"

    } else {

        & .\invoke-docker-build.ps1 nanoserver $env:APPVEYOR_BUILD_VERSION

        docker tag oneidentity/safeguard-ps:${env:APPVEYOR_BUILD_VERSION}-nanoserver oneidentity/safeguard-ps:${env:APPVEYOR_BUILD_VERSION}-windows

    }

test: off
deploy_script:
- ps: >-
    Publish-Module -Name safeguard-ps -NuGetApiKey $env:PsGalleryApiKey -Verbose -SkipAutomaticTags -Force

    if ([bool](Import-PowerShellDataFile (Join-Path (Get-Module safeguard-ps).ModuleBase safeguard-ps.psd1)).PrivateData.PSData.Prerelease) {

        Write-Host "Not publishing docker images for pre-release build"

    } else {

        docker login -u petrsnd -p $DockerHubAccessToken

        docker push oneidentity/safeguard-ps:${APPVEYOR_BUILD_VERSION}-nanoserver

        docker logout

    }

notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: safeguard-ps build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
